### ISSUE TITLE
GL window won't appear in Robofont v1.7.3

### ISSUE THREAD

**Issue by ltwp** [ghostlines/ghostlines-robofont#13]
Window won't appear, though focus comes off of the main Robofont window, when the extension icon is clicked. 

Here's the traceback I get:

```
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 484, in windowDidBecomeMain_
    self._alertBindings("became main")
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 455, in _alertBindings
    return callback(self)
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/windows/ufo_delivery_window.py", line 42, in fetch_applicants
    self.window.applicants.fetch()
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/applicant_list.py", line 70, in fetch
    registry = response.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 818, in json
    self.content.decode(encoding), **kwargs
  File "json/__init__.pyc", line 338, in loads
  File "json/decoder.pyc", line 366, in decode
  File "json/decoder.pyc", line 384, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 211, in action_
    self.callback(sender)
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/toolbar.py", line 55, in openSender
    UFODeliveryWindow(CurrentFont()).open()
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/windows/ufo_delivery_window.py", line 57, in open
    self.window.open()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 236, in open
    self.show()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 263, in show
    self._window.makeKeyAndOrderFront_(None)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 484, in windowDidBecomeMain_
    self._alertBindings("became main")
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 455, in _alertBindings
    return callback(self)
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/windows/ufo_delivery_window.py", line 42, in fetch_applicants
    self.window.applicants.fetch()
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/applicant_list.py", line 70, in fetch
    registry = response.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 818, in json
    self.content.decode(encoding), **kwargs
  File "json/__init__.pyc", line 338, in loads
  File "json/decoder.pyc", line 366, in decode
  File "json/decoder.pyc", line 384, in raw_decode
ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "lib/doodleDelegate.pyc", line 169, in sendEvent_
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 211, in action_
    self.callback(sender)
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/toolbar.py", line 55, in openSender
    UFODeliveryWindow(CurrentFont()).open()
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/windows/ufo_delivery_window.py", line 57, in open
    self.window.open()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 236, in open
    self.show()
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 263, in show
    self._window.makeKeyAndOrderFront_(None)
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 484, in windowDidBecomeMain_
    self._alertBindings("became main")
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaWindows.py", line 455, in _alertBindings
    return callback(self)
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/windows/ufo_delivery_window.py", line 42, in fetch_applicants
    self.window.applicants.fetch()
  File "/Users/lukas/Library/Application Support/RoboFont/plugins/Ghostlines.roboFontExt/lib/ghostlines/applicant_list.py", line 70, in fetch
    registry = response.json()
  File "/Library/Python/2.7/site-packages/requests/models.py", line 818, in json
    self.content.decode(encoding), **kwargs
  File "json/__init__.pyc", line 338, in loads
  File "json/decoder.pyc", line 366, in decode
  File "json/decoder.pyc", line 384, in raw_decode
ValueError: No JSON object could be decoded
```

**Comment by jackjennings** [comment]
Figured this out—there was an issue on the server side that was sending bad info back.
